src/Entity/Servicerendu.php
<?php
namespace App\Entity;

use Declic3000\Pelican\Entity\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * Servicerendu
 *
 * @ORM\Table(name="asso_servicerendus", indexes={@ORM\Index(name="date_debut", columns={"date_debut"}), @ORM\Index(name="date_fin", columns={"date_fin"}), @ORM\Index(name="id_entite", columns={"id_entite"}), @ORM\Index(name="id_prestation", columns={"id_prestation"}), @ORM\Index(name="id_membre", columns={"id_membre"}), @ORM\Index(name="asso_servicerendus_fi_8471d1", columns={"origine"}), @ORM\Index(name="id_piece", columns={"id_piece"})})
 * @ORM\Entity
 */
class Servicerendu extends Entity
{
    use TimestampableEntity;

    /**
     *
     * @var integer
     *
     * @ORM\Column(name="id_servicerendu", type="bigint", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $idServicerendu;


    /**
     *
     * @var float
     *
     * @ORM\Column(name="montant", type="float", precision=12, scale=2, nullable=false)
     */
    protected $montant;

    /**
     *
     * @var \DateTime
     *
     * @ORM\Column(name="date_enregistrement", type="date", nullable=true)
     */
    protected $dateEnregistrement;

    /**
     *
     * @var \DateTime
     *
     * @ORM\Column(name="date_debut", type="date", nullable=false)
     */
    protected $dateDebut;

    /**
     *
     * @var \DateTime
     *
     * @ORM\Column(name="date_fin", type="date", nullable=false)
     */
    protected $dateFin ;

    /**
     *
     * @var integer
     *
     * @ORM\Column(name="origine", type="integer", nullable=true)
     */
    protected $origine;

    /**
     *
     * @var integer
     *
     * @ORM\Column(name="premier", type="integer", nullable=true)
     */
    protected $premier = '0';

    /**
     *
     * @var integer
     *
     * @ORM\Column(name="dernier", type="integer", nullable=true)
     */
    protected $dernier = '0';

    /**
     *
     * @var Entite
     *
     * @ORM\ManyToOne(targetEntity="Entite")
     * @ORM\JoinColumn(name="id_entite", referencedColumnName="id_entite", onDelete="SET NULL")
     */
    protected $entite ;

    /**
     *
     * @var Prestation
     *
     * @ORM\ManyToOne(targetEntity="Prestation", inversedBy="servicerendus")
     * @ORM\JoinColumn(name="id_prestation", referencedColumnName="id_prestation", onDelete="SET NULL")
     */
    protected $prestation;

    /**
     *
     * @var integer
     *
     * @ORM\Column(name="regle", type="integer", nullable=false)
     */
    protected $regle = 1;

    /**
     *
     * @var Piece
     *
     * @ORM\ManyToOne(targetEntity="Piece", inversedBy="servicerendus")
     * @ORM\JoinColumn(name="id_piece", referencedColumnName="id_piece", onDelete="SET NULL")
     */
    protected $piece;


    /**
     * @var string
     *
     * @ORM\Column(name="etat_gestion", type="string", length=10, nullable=true)
     */
    protected $etatGestion = 'attente';
    
    
    /**
     *
     * @var string
     *
     * @ORM\Column(name="observation", type="text", length=16777215, nullable=true)
     */
    protected $observation;


    /**
     *
     * @var float
     *
     * @ORM\Column(name="quantite", type="float", precision=10, scale=0, nullable=false)
     */
    protected $quantite = '1';

    
    
    
    /**
     *
     * @var Individu
     *
     * @ORM\ManyToOne(targetEntity="Individu")
     * @ORM\JoinColumn(name="qui_cree", referencedColumnName="id_individu", onDelete="SET NULL")
     */
    protected $quiCree ;
    
    /**
     *
     * @var Individu
     *
     * @ORM\ManyToOne(targetEntity="Individu")
     * @ORM\JoinColumn(name="qui_maj", referencedColumnName="id_individu", onDelete="SET NULL")
     */
    protected $quiMaj ;
    
    
    
    

    


    /**
     *
     * @ORM\ManyToOne(targetEntity="Membre", inversedBy="servicerendus")
     * @ORM\JoinColumn(name="id_membre", referencedColumnName="id_membre", onDelete="SET NULL")
     */
    protected $membre;
    
    
    
    /**
     * Many mots have Many Individus.
     *
     * @ORM\ManyToMany(targetEntity="Individu", inversedBy="servicerendus")
     * @ORM\JoinTable(name="asso_servicerendus_individus",
     *  joinColumns={@ORM\JoinColumn(name="id_servicerendu", referencedColumnName="id_servicerendu")},
     *  inverseJoinColumns={@ORM\JoinColumn(name="id_individu", referencedColumnName="id_individu")}
     * )
     */
    protected $individus;
    
    
    /**
     * @ORM\OneToMany(targetEntity="Servicepaiement", mappedBy="servicerendu", cascade={"all"})
     */
    protected $servicepaiements;
    
    
    
    public function __construct()
    {
        $this->individus = new ArrayCollection();
        $this->servicepaiements = new ArrayCollection();
        
    }




    
    
    /**
     * @return number
     */
    public function getIdServicerendu()
    {
        return $this->idServicerendu;
    }

    /**
     *
     */
    public function setIdServicerendu( $id_servicerendu)
    {
        $this->idServicerendu = $id_servicerendu;
    }

    /**
     * @return number
     */
    public function getMontant()
    {
        return $this->montant;
    }



    /**
     * @return number
     */
    public function getMontantTotal()
    {
        return  $this->montant * $this->quantite;
    }


    /**
     * @return number
     */
    public function getMontantRestantAPayer()
    {

        $montant =  $this->getMontantTotal();
        $tab_sp = $this->getServicepaiements();
        if ($tab_sp){
            foreach($tab_sp as $sp){
                $montant -= $sp->getMontant();
            }
        }
        return $montant;
    }

    /**
     * @return number
     */
    public function getMontantPaye()
    {
        $montant = 0;
        $tab_sp = $this->getServicepaiements();
        if ($tab_sp){
            foreach($tab_sp as $sp){
                $montant += $sp->getMontant();
            }
        }
        return $montant;
    }



    /**
     * @return \DateTime
     */
    public function getDateEnregistrement()
    {
        return $this->dateEnregistrement;
    }

    /**
     * @return \DateTime
     */
    public function getDateDebut()
    {
        return $this->dateDebut;
    }

    /**
     * @return \DateTime
     */
    public function getDateFin()
    {
        return $this->dateFin;
    }

    /**
     * @return number
     */
    public function getOrigine()
    {
        return $this->origine;
    }

    /**
     * @return number
     */
    public function getPremier()
    {
        return $this->premier;
    }

    /**
     * @return number
     */
    public function getDernier()
    {
        return $this->dernier;
    }

    /**
     * @return \App\Entity\Entite
     */
    public function getEntite()
    {
        return $this->entite;
    }

    /**
     * @return \App\Entity\Prestation
     */
    public function getPrestation()
    {
        return $this->prestation;
    }

    /**
     * @return \App\Entity\Individu
     */
    public function getQuiCree()
    {
        return $this->quiCree;
    }

    /**
     * @return \App\Entity\Individu
     */
    public function getQuiMaj()
    {
        return $this->quiMaj;
    }

    /**
     * @param \App\Entity\Individu $quiCree
     */
    public function setQuiCree($quiCree)
    {
        $this->quiCree = $quiCree;
    }

    /**
     * @param \App\Entity\Individu $quiMaj
     */
    public function setQuiMaj($quiMaj)
    {
        $this->quiMaj = $quiMaj;
    }




    /**
     * @return number
     */
    public function getRegle()
    {
        return $this->regle;
    }

    /**
     * @return \App\Entity\Piece
     */
    public function getPiece()
    {
        return $this->piece;
    }



    /**
     * @return number
     */
    public function getEtatGestion()
    {
        return $this->etatGestion;
    }


    public function estCloture(){
        return $this->getEtatGestion()!=='attente' || $this->getEtatGestion()===null;

    }


    /**
     * @return string
     */
    public function getObservation()
    {
        return $this->observation;
    }

    /**
     * @return number
     */
    public function getQuantite()
    {
        return $this->quantite;
    }
    
    /**
     * @return float
     */
    public function getTotal()
    {
        return $this->quantite*$this->montant;
    }





    /**
     * @return mixed
     */
    public function getMembre()
    {
        return $this->membre;
    }



    /**
     * @param number $montant
     */
    public function setMontant($montant)
    {
        $this->montant = $montant;
    }

    /**
     * @param \DateTime $dateEnregistrement
     */
    public function setDateEnregistrement($dateEnregistrement)
    {
        $this->dateEnregistrement = $dateEnregistrement;
    }

    /**
     * @param \DateTime $dateDebut
     */
    public function setDateDebut($dateDebut)
    {
        $this->dateDebut = $dateDebut;
    }

    /**
     * @param \DateTime $dateFin
     */
    public function setDateFin($dateFin)
    {
        $this->dateFin = $dateFin;
    }

    /**
     * @param number $origine
     */
    public function setOrigine($origine)
    {
        $this->origine = $origine;
    }

    /**
     * @param number $premier
     */
    public function setPremier($premier)
    {
        $this->premier = $premier;
    }

    /**
     * @param number $dernier
     */
    public function setDernier($dernier)
    {
        $this->dernier = $dernier;
    }

    /**
     * @param \App\Entity\Entite $entite
     */
    public function setEntite($entite)
    {
        $this->entite = $entite;
    }

    /**
     * @param \App\Entity\Prestation $prestation
     */
    public function setPrestation($prestation)
    {
        $this->prestation = $prestation;
    }

    /**
     * @param number $regle

src/Controller/Asso/AccueilController.php
<?php

namespace App\Controller\Asso;

use App\Action\ServicerenduAction;
use App\Entity\Zone;
use App\Service\Bousole;
use Declic3000\Pelican\Service\Bigben;
use Declic3000\Pelican\Service\Selecteur;
use Symfony\Component\Routing\Annotation\Route;
use Declic3000\Pelican\Service\Controller;
use App\Service\Statisticien;



class AccueilController extends Controller
{
    /**
     * @Route("/", name="accueil")
     */
    public function index(Statisticien $statiticien)
    {

        $stat = $statiticien->getStatMembre();
        $stat['nb_ok_pourcentage']= ($stat['nb']>0) ? floor(($stat['nb_ok']/$stat['nb'])*100) : 0;
        $args_twig = $this->suc->pref('timeline.accueil');
        $args_twig= array_merge($args_twig,[
            'tab_operations'=> $this->log->getTimeline('accueil'),
            'stat_adh'=>$stat
        ]);

        
        return $this->render($this->sac->fichier_twig(),$args_twig);
    }


    /**
     * @Route("/test", name="test")
     */
    public function test(Statisticien $statiticien,Bigben $bigben,ServicerenduAction $sra)
    {

        $args =['id_individu'=>8843];

        $filename = '/var/www/simplasso/var/upload/LDH_LILLE_adherents.ods';

        /** Create a new Xls Reader  **/
        $reader = new \PhpOffice\PhpSpreadsheet\Reader\Ods();

        $spreadsheet = $reader->load($filename);
        exit();


        $tache = $this->createTache("geo_position",[],$args);

        $tache->tache_run();

        $periode = $this->sac->conf('systeme.periode.membre');
        foreach($periode as $prestation_groupe => &$dates){
            $tab_temp=[];
               $t0 =  array_shift($dates);
            foreach($dates as $date){
                $date_debut = new \DateTime($t0);
                $date_fin = (new \DateTime($date))->sub(new \DateInterval('P1D'));
                $tab_temp[]=[
                    'date_debut'=>$date_debut->format('d/m/Y'),
                    'date_fin'=>$date_fin->format('d/m/Y'),
                    'periode' => $bigben->date_periode($date_debut,$date_fin)
                ];
                $t0=$date;
            }
            $dates = $tab_temp;
        }
        $args_rep=[];
        $args_rep['periode'] =$periode;
        return $this->render('sys/test.html.twig',$args_rep);
    }


    /**
     * @Route("/test_geos", name="test_geos")
     */
    public function test_geos(Bousole $bousole)
    {

        $em = $this->getDoctrine()->getManager();
        $db = $em->getConnection();
        $tab_zone = $em->getRepository(Zone::class)->findAll();

        $tab_position= $db->fetchAll('SELECT id_individu as id, lat, lon FROM geo_positions p,geo_positions_individus pl WHERE p.id_position = pl.id_position LIMIT 0,1000');
        $tab_gis = [];
        foreach ($tab_position as $g) {
            $tab_gis[$g['lon'] . ' ' . $g['lat']][] = $g['id'];
        }
        foreach($tab_zone as $zone){
            $tab_id_objet = $bousole->pointDansLaZone($zone,$tab_gis);
        }
        exit();

    }



}

src/Controller/Asso/CourrierCotisationController.php
<?php

namespace App\Controller\Asso;

use App\Entity\Courrier;

use Symfony\Component\Routing\Annotation\Route;
use Declic3000\Pelican\Service\Controller;
use App\Form\CarteAdherentType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Entity\Log;
use App\Entity\DocumentLien;
use Declic3000\Pelican\Component\Form\PreferenceFormBuilder;

use Declic3000\Pelican\Service\Selecteur;
use Declic3000\Pelican\Service\Chargeur;
use App\Service\Encarteur;


/**
 * @Route("/courrier_cotisation")
 */
class CourrierCotisationController extends Controller
{




    /**
     * @Route("/ajout/{type}/{id}", name="courrier_accueil_ajout")
     */

    function courrier_accueil_ajout(string $type, int $id)
    {
        $conf = $this->conf('courrier_cotisation');
        $em = $this->getDoctrine()->getManager();
        $type= ($type!='accueil')?'renouvelement':$type;
        $courrier = $em->getRepository(Courrier::class)->find($conf['courrier_'.$type]);
        $courrier_ext = $this->generateObjetExt($courrier);
        $courrier_ext->ajouterDestinataire($id);
        $this->log('ACC', 'COU', $courrier);
        return $this->json(['ok' => true, 'message'=>'expediteur_ajouté']);


    }


}

src/Controller/Asso/EntiteController.php
<?php
namespace App\Controller\Asso;

use App\EntityExtension\EntiteExt;
use App\Form\LogoType;
use Declic3000\Pelican\Service\Ged;
use Symfony\Component\Routing\Annotation\Route;
use Declic3000\Pelican\Service\ControllerObjet;
use App\Entity\Entite;

/**
 *
 * @Route("/entite")
 */
class EntiteController extends ControllerObjet
{


    /**
     *
     * @Route("/", name="entite_index", methods="GET")
     */
    public function index()
    {
        return $this->index_defaut();
    }
    
    
    /**
     *
     * @Route("/new", name="entite_new", methods="GET|POST")
     */
    public function new()
    {
        return $this->new_defaut();
    }
    
    /**
     * @Route("/{idEntite}/edit", name="entite_edit", methods="GET|POST")
     */
    
    public function edit(Entite $ob)
    {
        return $this->edit_defaut($ob);
    }
    
    
    /**
     * @Route("/{idEntite}", name="entite_delete", methods="DELETE")
     */
    
    public function delete(Entite $ob)
    {
        return $this->delete_defaut($ob);
        
    }


    /**
     * @Route("/{idEntite}/logo", name="entite_logo", methods="GET|POST")
     */

    public function logo(Entite $ob,Ged $ged)
    {
        return $this->logo_defaut($ged,$ob);
    }




    /**
     * @Route("/{idEntite}", name="entite_show", methods="GET|POST")
     */
    
    public function show(Entite $ob,Ged $ged)
    {
        $ob_ext = new EntiteExt($ob,$this->sac,$this->getDoctrine()->getManager());
        $args=['idEntite'=>$ob->getPrimaryKey()];
        $form_logo  = $this->generateForm('logo',LogoType::class,[],[],true,$args);
        $ged->traitement_form_ged('logo_image', $ob->getPrimaryKey(), 'entite', 'logo');
        $args_twig = [
            'objet_data' => $ob,
            'objet_data_ext' => $ob_ext,
            'form_logo' => $form_logo->createView()
        ];
        return $this->render($this->sac->fichier_twig(), $args_twig);
    }
    
}

src/Controller/Asso/PrixController.php
<?php

namespace App\Controller\Asso;

use Symfony\Component\Routing\Annotation\Route;
use Declic3000\Pelican\Service\ControllerObjet;
use App\Entity\Prix;

/**
 *
 * @Route("/prix")
 */
class PrixController extends ControllerObjet
{

    /**
     *
     * @Route("/", name="prix_index", methods="GET")
     */
    public function index()
    {
        return $this->index_defaut();
    }
    
    
    /**
     *
     * @Route("/new", name="prix_new", methods="GET|POST")
     */
    public function new()
    {
        $id_prestation = $this->requete->get('id_prestation');
        return $this->new_defaut(['id_prestation'=>$id_prestation]);
    }


    /**
     * @Route("/{idPrix}/edit", name="prix_edit", methods="GET|POST")
     */
    
    public function edit(Prix $ob)
    {
        return $this->edit_defaut($ob);
    }
    
    
    /**
     * @Route("/{idPrix}", name="prix_delete", methods="DELETE")
     */
    
    public function delete(Prix $ob)
    {
        return $this->delete_defaut($ob);
        
    }
    
    /**
     * @Route("/{idPrix}", name="prix_show", methods="GET")
     */
    
    public function show(Prix $ob)
    {
        return $this->show_defaut($ob);
        
    }
}

templates/asso/servicerendu/_form.html.twig
{% form_theme form with ['form_large.html.twig'] %}


{% set mode_saisie = 'tortue' %}{% if pref(objet_en_cours()~'.form.mode_saisie')==1 %}{% set mode_saisie = 'lievre' %}{% endif %}
	<div class="formulaire {{ mode_saisie }}">
    	<div class="en_haut_a_droite float-right option_form ">


    	{% if pref_exist(objet_en_cours()~'|form') and form_pref is not defined %}
            {% set form_pref = objet_en_cours()~'|form' %}
        {% endif %}
            {% if form_pref is defined %}
            <a href="{{ path('preference_edit',{'pref': form_pref}) }}"    class="btn btn-sm btn-secondary modal-form">
                <i class="fa fa-cog"></i>
            </a>
             {% endif %}
		</div>
    
    
{{ form_start(form) }}

{% set section = sac('objet')~'_liste' %}
{% set prestation_type = sac('alias_valeur') %}



  

            {% form_theme form with ['bootstrap_4_horizontal_layout.html.twig'] %}

            {{ form_start(form) }}
            {{ form_errors(form) }}

            <fieldset class="fieldset_servicerendu">
                <div class="panel-group" id="accordion">

                    {% if form.objet_beneficiaire is defined %}
                        {{ form_row(form.objet_beneficiaire) }}
                        {{ form_row(form.id_objet_beneficiaire) }}
                    {% endif %}

                    {% if not modification %}
                       		 {{ form_row(form.id_entite) }}

                             {% if lot %}
                                 {{ form_row(form.id_prestationlot) }}
                                {% for i in 0..nb_prestation-1 %}
                                    {% set nom_pr = 'pr'~i %}
                                    {% set form_prestation = form[nom_pr] %}

                                    <div class="panel panel-secondary panneau_prestation" id="prestation{{ i }}">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion"
                                                   href="#collapse{{ i }}">Prestation {{ i }}</a>
                                            </h4>
                                        </div>
                                        <div id="collapse{{ i }}" class="panel-collapse collapse">
                                            <div class="panel-body">

                                                {% include('asso/servicerendu/form_line.html.twig'  )  with {'form_prestation':form[nom_pr],'modification':modification} %}

                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% else %}

                              {% include('asso/servicerendu/form_line.html.twig'  ) with {'form_prestation':form['pr0'],'modification':modification}  %}
                            {% endif %}


     	            {% else %}

                      {% include('asso/servicerendu/form_line.html.twig'  ) with {'form_prestation':form,'modification':modification} %}


                    {% endif %}
                   

                      
                </div>


            </fieldset>

            {% if not modification %}

            {{ form_row(form.reglement_question) }}

            <fieldset class="fieldset_reglement">
                <legend>Réglement</legend>
                <div class="panel">
                    <div class="panel-title">Nouveau paiement
                    </div>
                    <div class="panel-body">
                        {{ form_row(form.reglement.montant) }}
                        {{ form_row(form.reglement.tresor) }}

                        <div class="form-group">
                                <div class="row">
                                {{ form_errors(form.reglement.date_cheque) }}
                                {{ form_errors(form.reglement.date_enregistrement) }}

                                {{ form_label(form.reglement.date_enregistrement) }}
                                <div class="col-sm-3">
                                    {{ form_widget(form.reglement.date_enregistrement) }}
                                </div>
                                    {{ form_label(form.reglement.date_cheque) }}
                                <div class="col-sm-3 champs_date_enregistrement">
                                    {{ form_widget(form.reglement.date_cheque) }}
                                </div>

                                </div>
                            </div>

                            {{ form_row(form.reglement.numero) }}
                            {{ form_row(form.reglement.observation) }}

                    </div>
                </div>
                    {% if  form.service_paiement.solde is defined %}
                    <div class="panel">
                        <div class="panel-title">Utiliser un paiement existant non assigné.</div>
                        <div class="panel-body">
                        {{ form_widget(form.service_paiement.solde) }}
                        </div>
                    </div>
                        {% else %}
                            {{ form_widget(form.service_paiement) }}
                    {% endif %}
            </fieldset>
            {% endif %}
            {{ form_end(form) }}


            <script type="application/javascript">
                {% if not modification %}
                    var variable_servicerendu_form = {
                        combinaison: {{ tab_prochains_servicerendu|json_encode|raw }},
                        periode: {{ periode|json_encode|raw }},
                        nb_prestation: {{ nb_prestation }},
                        lot: {% if lot %}true{% else %}false{% endif %},
                        {% if lot %}
                        combinaison_lot: {{ tab_prestationlot|json_encode|raw }},
                        {% endif %}
                        objet_beneficiaire:'{{objet_beneficiaire }}',
                        prestation_type:'{{prestation_type }}',
                        soldes:{{ tab_soldes|json_encode|raw }},
                        modepaiement:{{ tab_modepaiements|json_encode|raw }},
                        nom_formulaire: '{{ form_name }}',
                        modification: {{ modification }}+0

                    };

                    init_servicerendu_form(variable_servicerendu_form);
                {% endif %}
            </script>

{{ form_end(form) }}
</div>

templates/asso/servicerendu/edit.html.twig
{% extends 'base'~layout_cplt()~'.html.twig' %}

{% block title %}Edit {{ sac('objet') }}{% endblock %}

{% block body %}
    <h1>Edit sac('objet')</h1>
    {% block formulaire %}
    {{ include('asso/servicerendu/_form.html.twig', {'modification':true,'button_label': 'Update'}) }}
    {% endblock %}
{% endblock %}

templates/asso/servicerendu/form_line.html.twig
{% form_theme form with ['form_large.html.twig'] %}


    {{ form_row(form_prestation.prestation) }}


<div class="form-group">
    <div class="row">
    {{ form_label(form_prestation.date_enregistrement) }}
    <div class="col-sm-4">
        {{ form_widget(form_prestation.date_enregistrement) }}
    </div>
    </div>

    {#
    <div class="form-group ">
        <div class="col-sm-4"> </div>
    
        
        <label class="col-sm-1 control-badge badge_tva">tva</label>
        <div class="col-sm-4 champs_taux">
            {{ form_widget(form_prestation.taux) }}
        </div>
        {{ form_errors(form_prestation.taux) }}
        
    
    #}
</div>


<div class="form-group champs_dates">
    <div class="row">
    {{ form_label(form_prestation.periode) }}
    <div class="col-sm-9">
        {{ form_widget(form_prestation.periode) }}
    </div>
    {{ form_errors(form_prestation.periode) }}
    {{ form_errors(form_prestation.periode) }}
    </div>
</div>

<div class="form-group champs_dates">
    <div class="row">
    {{ form_label(form_prestation.date_debut) }}
    <div class="col-sm-4">
        {{ form_widget(form_prestation.date_debut) }}
    </div>
    <label class="col-sm-1 control-label champs_date_fin">au</label>
    <div class="col-sm-4 champs_date_fin">
        {{ form_widget(form_prestation.date_fin) }}
    </div>
    {{ form_errors(form_prestation.date_debut) }}
    {{ form_errors(form_prestation.date_fin) }}
    </div>
</div>

<div class="form-group champs_abo">
    <div class="row">
    {{ form_label(form_prestation.premier) }}
    <div class="col-sm-4">
        {{ form_widget(form_prestation.premier) }}
    </div>
    <label class="col-sm-1 control-label champs_date_fin">au</label>
    <div class="col-sm-4 champs_date_fin">
        {{ form_widget(form_prestation.dernier) }}
    </div>
    {{ form_errors(form_prestation.premier) }}
    {{ form_errors(form_prestation.dernier) }}

</div>
</div>
<div class="form-group">
    <div class="row">

        {{ form_label(form_prestation.montant) }}
        <div class="col-sm-3">
            {{ form_widget(form_prestation.montant) }}
        </div>


        <div class="col-sm-2 champs_quantite" >
            <label class="control-label">*</label>
            {{ form_widget(form_prestation.quantite) }}
        </div>
        <label class="col-sm-1 control-label champs_total"> = </label>
        <div class="col-sm-3">
            {{ form_widget(form_prestation.total) }}
        </div>

    </div>


</div>

{{ form_row(form_prestation.observation) }}

templates/asso/servicerendu/index.html.twig
{% extends 'objet/index.html.twig' %}